services:
  - type: web
    name: point-of-sale
    env: node
    buildCommand: npm install --force && npm run build
    startCommand: npm run start:production
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
